# Generated by Django 3.1 on 2020-08-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(upload_to='', verbose_name='Превью')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_visible', models.BooleanField(verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Папка')),
                ('preview', models.ImageField(upload_to='', verbose_name='Превью')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('html', 'html'), ('image', 'Изображение'), ('file', 'Файл')], max_length=5, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(verbose_name='порядок')),
                ('file', models.FileField(upload_to='upload/%Y/%m/%d/', verbose_name='Файл')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='courses.document')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.folder'),
        ),
    ]
